//*
// LED Control Service.
//
// Service that enables user to control LEDs

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/led.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedControl_ListLeds_FullMethodName              = "/hal.ledcontrol.LedControl/ListLeds"
	LedControl_ListAvailableTriggers_FullMethodName = "/hal.ledcontrol.LedControl/ListAvailableTriggers"
	LedControl_GetState_FullMethodName              = "/hal.ledcontrol.LedControl/GetState"
	LedControl_SetTrigger_FullMethodName            = "/hal.ledcontrol.LedControl/SetTrigger"
	LedControl_SetState_FullMethodName              = "/hal.ledcontrol.LedControl/SetState"
)

// LedControlClient is the client API for LedControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedControlClient interface {
	// List all available LEDs
	ListLeds(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LedListResponse, error)
	// List all available triggers
	ListAvailableTriggers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAvailableTriggersResponse, error)
	// Get the current state of a specific LED
	GetState(ctx context.Context, in *LedNameRequest, opts ...grpc.CallOption) (*LedStateResponse, error)
	// Set trigger of a specific LED
	SetTrigger(ctx context.Context, in *LedTriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Turn a specific LED on or off
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type ledControlClient struct {
	cc grpc.ClientConnInterface
}

func NewLedControlClient(cc grpc.ClientConnInterface) LedControlClient {
	return &ledControlClient{cc}
}

func (c *ledControlClient) ListLeds(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LedListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedListResponse)
	err := c.cc.Invoke(ctx, LedControl_ListLeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledControlClient) ListAvailableTriggers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListAvailableTriggersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableTriggersResponse)
	err := c.cc.Invoke(ctx, LedControl_ListAvailableTriggers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledControlClient) GetState(ctx context.Context, in *LedNameRequest, opts ...grpc.CallOption) (*LedStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedStateResponse)
	err := c.cc.Invoke(ctx, LedControl_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledControlClient) SetTrigger(ctx context.Context, in *LedTriggerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LedControl_SetTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledControlClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LedControl_SetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedControlServer is the server API for LedControl service.
// All implementations must embed UnimplementedLedControlServer
// for forward compatibility.
type LedControlServer interface {
	// List all available LEDs
	ListLeds(context.Context, *emptypb.Empty) (*LedListResponse, error)
	// List all available triggers
	ListAvailableTriggers(context.Context, *emptypb.Empty) (*ListAvailableTriggersResponse, error)
	// Get the current state of a specific LED
	GetState(context.Context, *LedNameRequest) (*LedStateResponse, error)
	// Set trigger of a specific LED
	SetTrigger(context.Context, *LedTriggerRequest) (*emptypb.Empty, error)
	// Turn a specific LED on or off
	SetState(context.Context, *SetStateRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedLedControlServer()
}

// UnimplementedLedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedControlServer struct{}

func (UnimplementedLedControlServer) ListLeds(context.Context, *emptypb.Empty) (*LedListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeds not implemented")
}
func (UnimplementedLedControlServer) ListAvailableTriggers(context.Context, *emptypb.Empty) (*ListAvailableTriggersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableTriggers not implemented")
}
func (UnimplementedLedControlServer) GetState(context.Context, *LedNameRequest) (*LedStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedLedControlServer) SetTrigger(context.Context, *LedTriggerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTrigger not implemented")
}
func (UnimplementedLedControlServer) SetState(context.Context, *SetStateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedLedControlServer) mustEmbedUnimplementedLedControlServer() {}
func (UnimplementedLedControlServer) testEmbeddedByValue()                    {}

// UnsafeLedControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedControlServer will
// result in compilation errors.
type UnsafeLedControlServer interface {
	mustEmbedUnimplementedLedControlServer()
}

func RegisterLedControlServer(s grpc.ServiceRegistrar, srv LedControlServer) {
	// If the following call panics, it indicates UnimplementedLedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedControl_ServiceDesc, srv)
}

func _LedControl_ListLeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedControlServer).ListLeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedControl_ListLeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedControlServer).ListLeds(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedControl_ListAvailableTriggers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedControlServer).ListAvailableTriggers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedControl_ListAvailableTriggers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedControlServer).ListAvailableTriggers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedControl_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedControlServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedControl_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedControlServer).GetState(ctx, req.(*LedNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedControl_SetTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedControlServer).SetTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedControl_SetTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedControlServer).SetTrigger(ctx, req.(*LedTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedControl_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedControlServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedControl_SetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedControlServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedControl_ServiceDesc is the grpc.ServiceDesc for LedControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hal.ledcontrol.LedControl",
	HandlerType: (*LedControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLeds",
			Handler:    _LedControl_ListLeds_Handler,
		},
		{
			MethodName: "ListAvailableTriggers",
			Handler:    _LedControl_ListAvailableTriggers_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _LedControl_GetState_Handler,
		},
		{
			MethodName: "SetTrigger",
			Handler:    _LedControl_SetTrigger_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _LedControl_SetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/led.proto",
}
