//*
// LED Control Service.
//
// Service that enables user to control LEDs

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/led.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnState int32

const (
	OnState_OFF OnState = 0
	OnState_ON  OnState = 1
	OnState_ERR OnState = 2
)

// Enum value maps for OnState.
var (
	OnState_name = map[int32]string{
		0: "OFF",
		1: "ON",
		2: "ERR",
	}
	OnState_value = map[string]int32{
		"OFF": 0,
		"ON":  1,
		"ERR": 2,
	}
)

func (x OnState) Enum() *OnState {
	p := new(OnState)
	*p = x
	return p
}

func (x OnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_led_proto_enumTypes[0].Descriptor()
}

func (OnState) Type() protoreflect.EnumType {
	return &file_pkg_led_proto_enumTypes[0]
}

func (x OnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnState.Descriptor instead.
func (OnState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{0}
}

type LedNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedName       string                 `protobuf:"bytes,1,opt,name=ledName,proto3" json:"ledName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedNameRequest) Reset() {
	*x = LedNameRequest{}
	mi := &file_pkg_led_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedNameRequest) ProtoMessage() {}

func (x *LedNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_led_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedNameRequest.ProtoReflect.Descriptor instead.
func (*LedNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{0}
}

func (x *LedNameRequest) GetLedName() string {
	if x != nil {
		return x.LedName
	}
	return ""
}

type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trigger       string                 `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_pkg_led_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_led_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type LedListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedNames      []*LedNameRequest      `protobuf:"bytes,1,rep,name=ledNames,proto3" json:"ledNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedListResponse) Reset() {
	*x = LedListResponse{}
	mi := &file_pkg_led_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedListResponse) ProtoMessage() {}

func (x *LedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_led_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedListResponse.ProtoReflect.Descriptor instead.
func (*LedListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{2}
}

func (x *LedListResponse) GetLedNames() []*LedNameRequest {
	if x != nil {
		return x.LedNames
	}
	return nil
}

type ListAvailableTriggersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggers      []string               `protobuf:"bytes,1,rep,name=triggers,proto3" json:"triggers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableTriggersResponse) Reset() {
	*x = ListAvailableTriggersResponse{}
	mi := &file_pkg_led_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableTriggersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableTriggersResponse) ProtoMessage() {}

func (x *ListAvailableTriggersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_led_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableTriggersResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableTriggersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{3}
}

func (x *ListAvailableTriggersResponse) GetTriggers() []string {
	if x != nil {
		return x.Triggers
	}
	return nil
}

type LedStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         OnState                `protobuf:"varint,1,opt,name=state,proto3,enum=hal.ledcontrol.OnState" json:"state,omitempty"`
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedStateResponse) Reset() {
	*x = LedStateResponse{}
	mi := &file_pkg_led_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedStateResponse) ProtoMessage() {}

func (x *LedStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_led_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedStateResponse.ProtoReflect.Descriptor instead.
func (*LedStateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{4}
}

func (x *LedStateResponse) GetState() OnState {
	if x != nil {
		return x.State
	}
	return OnState_OFF
}

func (x *LedStateResponse) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *LedStateResponse) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type LedTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedName       string                 `protobuf:"bytes,1,opt,name=ledName,proto3" json:"ledName,omitempty"`
	Trigger       string                 `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedTriggerRequest) Reset() {
	*x = LedTriggerRequest{}
	mi := &file_pkg_led_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedTriggerRequest) ProtoMessage() {}

func (x *LedTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_led_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedTriggerRequest.ProtoReflect.Descriptor instead.
func (*LedTriggerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{5}
}

func (x *LedTriggerRequest) GetLedName() string {
	if x != nil {
		return x.LedName
	}
	return ""
}

func (x *LedTriggerRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type SetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedName       string                 `protobuf:"bytes,1,opt,name=ledName,proto3" json:"ledName,omitempty"`
	State         bool                   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Color         *string                `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	mi := &file_pkg_led_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_led_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_led_proto_rawDescGZIP(), []int{6}
}

func (x *SetStateRequest) GetLedName() string {
	if x != nil {
		return x.LedName
	}
	return ""
}

func (x *SetStateRequest) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *SetStateRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

var File_pkg_led_proto protoreflect.FileDescriptor

const file_pkg_led_proto_rawDesc = "" +
	"\n" +
	"\rpkg/led.proto\x12\x0ehal.ledcontrol\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x0eLedNameRequest\x12\x18\n" +
	"\aledName\x18\x01 \x01(\tR\aledName\"*\n" +
	"\x0eTriggerRequest\x12\x18\n" +
	"\atrigger\x18\x01 \x01(\tR\atrigger\"M\n" +
	"\x0fLedListResponse\x12:\n" +
	"\bledNames\x18\x01 \x03(\v2\x1e.hal.ledcontrol.LedNameRequestR\bledNames\";\n" +
	"\x1dListAvailableTriggersResponse\x12\x1a\n" +
	"\btriggers\x18\x01 \x03(\tR\btriggers\"\x80\x01\n" +
	"\x10LedStateResponse\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.hal.ledcontrol.OnStateR\x05state\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01B\b\n" +
	"\x06_color\"G\n" +
	"\x11LedTriggerRequest\x12\x18\n" +
	"\aledName\x18\x01 \x01(\tR\aledName\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\"f\n" +
	"\x0fSetStateRequest\x12\x18\n" +
	"\aledName\x18\x01 \x01(\tR\aledName\x12\x14\n" +
	"\x05state\x18\x02 \x01(\bR\x05state\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x00R\x05color\x88\x01\x01B\b\n" +
	"\x06_color*#\n" +
	"\aOnState\x12\a\n" +
	"\x03OFF\x10\x00\x12\x06\n" +
	"\x02ON\x10\x01\x12\a\n" +
	"\x03ERR\x10\x022\x8d\x03\n" +
	"\n" +
	"LedControl\x12C\n" +
	"\bListLeds\x12\x16.google.protobuf.Empty\x1a\x1f.hal.ledcontrol.LedListResponse\x12^\n" +
	"\x15ListAvailableTriggers\x12\x16.google.protobuf.Empty\x1a-.hal.ledcontrol.ListAvailableTriggersResponse\x12L\n" +
	"\bGetState\x12\x1e.hal.ledcontrol.LedNameRequest\x1a .hal.ledcontrol.LedStateResponse\x12G\n" +
	"\n" +
	"SetTrigger\x12!.hal.ledcontrol.LedTriggerRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\bSetState\x12\x1f.hal.ledcontrol.SetStateRequest\x1a\x16.google.protobuf.EmptyB\x11Z\x0f./protos;protosb\x06proto3"

var (
	file_pkg_led_proto_rawDescOnce sync.Once
	file_pkg_led_proto_rawDescData []byte
)

func file_pkg_led_proto_rawDescGZIP() []byte {
	file_pkg_led_proto_rawDescOnce.Do(func() {
		file_pkg_led_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_led_proto_rawDesc), len(file_pkg_led_proto_rawDesc)))
	})
	return file_pkg_led_proto_rawDescData
}

var file_pkg_led_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_led_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_led_proto_goTypes = []any{
	(OnState)(0),                          // 0: hal.ledcontrol.OnState
	(*LedNameRequest)(nil),                // 1: hal.ledcontrol.LedNameRequest
	(*TriggerRequest)(nil),                // 2: hal.ledcontrol.TriggerRequest
	(*LedListResponse)(nil),               // 3: hal.ledcontrol.LedListResponse
	(*ListAvailableTriggersResponse)(nil), // 4: hal.ledcontrol.ListAvailableTriggersResponse
	(*LedStateResponse)(nil),              // 5: hal.ledcontrol.LedStateResponse
	(*LedTriggerRequest)(nil),             // 6: hal.ledcontrol.LedTriggerRequest
	(*SetStateRequest)(nil),               // 7: hal.ledcontrol.SetStateRequest
	(*emptypb.Empty)(nil),                 // 8: google.protobuf.Empty
}
var file_pkg_led_proto_depIdxs = []int32{
	1, // 0: hal.ledcontrol.LedListResponse.ledNames:type_name -> hal.ledcontrol.LedNameRequest
	0, // 1: hal.ledcontrol.LedStateResponse.state:type_name -> hal.ledcontrol.OnState
	8, // 2: hal.ledcontrol.LedControl.ListLeds:input_type -> google.protobuf.Empty
	8, // 3: hal.ledcontrol.LedControl.ListAvailableTriggers:input_type -> google.protobuf.Empty
	1, // 4: hal.ledcontrol.LedControl.GetState:input_type -> hal.ledcontrol.LedNameRequest
	6, // 5: hal.ledcontrol.LedControl.SetTrigger:input_type -> hal.ledcontrol.LedTriggerRequest
	7, // 6: hal.ledcontrol.LedControl.SetState:input_type -> hal.ledcontrol.SetStateRequest
	3, // 7: hal.ledcontrol.LedControl.ListLeds:output_type -> hal.ledcontrol.LedListResponse
	4, // 8: hal.ledcontrol.LedControl.ListAvailableTriggers:output_type -> hal.ledcontrol.ListAvailableTriggersResponse
	5, // 9: hal.ledcontrol.LedControl.GetState:output_type -> hal.ledcontrol.LedStateResponse
	8, // 10: hal.ledcontrol.LedControl.SetTrigger:output_type -> google.protobuf.Empty
	8, // 11: hal.ledcontrol.LedControl.SetState:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_led_proto_init() }
func file_pkg_led_proto_init() {
	if File_pkg_led_proto != nil {
		return
	}
	file_pkg_led_proto_msgTypes[4].OneofWrappers = []any{}
	file_pkg_led_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_led_proto_rawDesc), len(file_pkg_led_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_led_proto_goTypes,
		DependencyIndexes: file_pkg_led_proto_depIdxs,
		EnumInfos:         file_pkg_led_proto_enumTypes,
		MessageInfos:      file_pkg_led_proto_msgTypes,
	}.Build()
	File_pkg_led_proto = out.File
	file_pkg_led_proto_goTypes = nil
	file_pkg_led_proto_depIdxs = nil
}
