//*
// DigitalIO Service.
//
// Service that enables a control of the Digital IO features of device

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/dio.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IOType int32

const (
	IOType_INPUT         IOType = 0
	IOType_OUTPUT        IOType = 1
	IOType_BIDIRECTIONAL IOType = 2
)

// Enum value maps for IOType.
var (
	IOType_name = map[int32]string{
		0: "INPUT",
		1: "OUTPUT",
		2: "BIDIRECTIONAL",
	}
	IOType_value = map[string]int32{
		"INPUT":         0,
		"OUTPUT":        1,
		"BIDIRECTIONAL": 2,
	}
)

func (x IOType) Enum() *IOType {
	p := new(IOType)
	*p = x
	return p
}

func (x IOType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IOType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_dio_proto_enumTypes[0].Descriptor()
}

func (IOType) Type() protoreflect.EnumType {
	return &file_pkg_dio_proto_enumTypes[0]
}

func (x IOType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IOType.Descriptor instead.
func (IOType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{0}
}

type IODirection int32

const (
	IODirection_IN  IODirection = 0
	IODirection_OUT IODirection = 1
)

// Enum value maps for IODirection.
var (
	IODirection_name = map[int32]string{
		0: "IN",
		1: "OUT",
	}
	IODirection_value = map[string]int32{
		"IN":  0,
		"OUT": 1,
	}
)

func (x IODirection) Enum() *IODirection {
	p := new(IODirection)
	*p = x
	return p
}

func (x IODirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IODirection) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_dio_proto_enumTypes[1].Descriptor()
}

func (IODirection) Type() protoreflect.EnumType {
	return &file_pkg_dio_proto_enumTypes[1]
}

func (x IODirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IODirection.Descriptor instead.
func (IODirection) EnumDescriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{1}
}

type IOState int32

const (
	IOState_ERROR IOState = 0
	IOState_LOW   IOState = 1
	IOState_HIGH  IOState = 2
)

// Enum value maps for IOState.
var (
	IOState_name = map[int32]string{
		0: "ERROR",
		1: "LOW",
		2: "HIGH",
	}
	IOState_value = map[string]int32{
		"ERROR": 0,
		"LOW":   1,
		"HIGH":  2,
	}
)

func (x IOState) Enum() *IOState {
	p := new(IOState)
	*p = x
	return p
}

func (x IOState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IOState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_dio_proto_enumTypes[2].Descriptor()
}

func (IOState) Type() protoreflect.EnumType {
	return &file_pkg_dio_proto_enumTypes[2]
}

func (x IOState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IOState.Descriptor instead.
func (IOState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{2}
}

type IODevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          IOType                 `protobuf:"varint,2,opt,name=type,proto3,enum=hal.digitalio.IOType" json:"type,omitempty"`
	Direction     IODirection            `protobuf:"varint,3,opt,name=direction,proto3,enum=hal.digitalio.IODirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IODevice) Reset() {
	*x = IODevice{}
	mi := &file_pkg_dio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IODevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IODevice) ProtoMessage() {}

func (x *IODevice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IODevice.ProtoReflect.Descriptor instead.
func (*IODevice) Descriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{0}
}

func (x *IODevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IODevice) GetType() IOType {
	if x != nil {
		return x.Type
	}
	return IOType_INPUT
}

func (x *IODevice) GetDirection() IODirection {
	if x != nil {
		return x.Direction
	}
	return IODirection_IN
}

// *
// Represents the ListDevices response data.
type DigitalIOListDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*IODevice            `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalIOListDeviceResponse) Reset() {
	*x = DigitalIOListDeviceResponse{}
	mi := &file_pkg_dio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalIOListDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalIOListDeviceResponse) ProtoMessage() {}

func (x *DigitalIOListDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalIOListDeviceResponse.ProtoReflect.Descriptor instead.
func (*DigitalIOListDeviceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{1}
}

func (x *DigitalIOListDeviceResponse) GetDevices() []*IODevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// *
// Represents the SetDirection request data.
type DigitalIOSetDirectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Direction     IODirection            `protobuf:"varint,2,opt,name=direction,proto3,enum=hal.digitalio.IODirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalIOSetDirectionRequest) Reset() {
	*x = DigitalIOSetDirectionRequest{}
	mi := &file_pkg_dio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalIOSetDirectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalIOSetDirectionRequest) ProtoMessage() {}

func (x *DigitalIOSetDirectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalIOSetDirectionRequest.ProtoReflect.Descriptor instead.
func (*DigitalIOSetDirectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{2}
}

func (x *DigitalIOSetDirectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DigitalIOSetDirectionRequest) GetDirection() IODirection {
	if x != nil {
		return x.Direction
	}
	return IODirection_IN
}

// *
// Represents the Read request data.
type DigitalIOReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalIOReadRequest) Reset() {
	*x = DigitalIOReadRequest{}
	mi := &file_pkg_dio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalIOReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalIOReadRequest) ProtoMessage() {}

func (x *DigitalIOReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalIOReadRequest.ProtoReflect.Descriptor instead.
func (*DigitalIOReadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{3}
}

func (x *DigitalIOReadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// *
// Represents the Read response data.
type DigitalIOReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         IOState                `protobuf:"varint,1,opt,name=state,proto3,enum=hal.digitalio.IOState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalIOReadResponse) Reset() {
	*x = DigitalIOReadResponse{}
	mi := &file_pkg_dio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalIOReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalIOReadResponse) ProtoMessage() {}

func (x *DigitalIOReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalIOReadResponse.ProtoReflect.Descriptor instead.
func (*DigitalIOReadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{4}
}

func (x *DigitalIOReadResponse) GetState() IOState {
	if x != nil {
		return x.State
	}
	return IOState_ERROR
}

// *
// Represents the Write request data.
type DigitalIOWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         IOState                `protobuf:"varint,2,opt,name=state,proto3,enum=hal.digitalio.IOState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalIOWriteRequest) Reset() {
	*x = DigitalIOWriteRequest{}
	mi := &file_pkg_dio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalIOWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalIOWriteRequest) ProtoMessage() {}

func (x *DigitalIOWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalIOWriteRequest.ProtoReflect.Descriptor instead.
func (*DigitalIOWriteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{5}
}

func (x *DigitalIOWriteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DigitalIOWriteRequest) GetState() IOState {
	if x != nil {
		return x.State
	}
	return IOState_ERROR
}

// *
// Represents the Attach response data.
type DigitalIOAttachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         IOState                `protobuf:"varint,2,opt,name=state,proto3,enum=hal.digitalio.IOState" json:"state,omitempty"`
	Error         int32                  `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalIOAttachResponse) Reset() {
	*x = DigitalIOAttachResponse{}
	mi := &file_pkg_dio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalIOAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalIOAttachResponse) ProtoMessage() {}

func (x *DigitalIOAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalIOAttachResponse.ProtoReflect.Descriptor instead.
func (*DigitalIOAttachResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dio_proto_rawDescGZIP(), []int{6}
}

func (x *DigitalIOAttachResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DigitalIOAttachResponse) GetState() IOState {
	if x != nil {
		return x.State
	}
	return IOState_ERROR
}

func (x *DigitalIOAttachResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *DigitalIOAttachResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_pkg_dio_proto protoreflect.FileDescriptor

const file_pkg_dio_proto_rawDesc = "" +
	"\n" +
	"\rpkg/dio.proto\x12\rhal.digitalio\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x01\n" +
	"\bIODevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.hal.digitalio.IOTypeR\x04type\x128\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x1a.hal.digitalio.IODirectionR\tdirection\"P\n" +
	"\x1bDigitalIOListDeviceResponse\x121\n" +
	"\adevices\x18\x01 \x03(\v2\x17.hal.digitalio.IODeviceR\adevices\"l\n" +
	"\x1cDigitalIOSetDirectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1a.hal.digitalio.IODirectionR\tdirection\"*\n" +
	"\x14DigitalIOReadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\x15DigitalIOReadResponse\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.hal.digitalio.IOStateR\x05state\"Y\n" +
	"\x15DigitalIOWriteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.hal.digitalio.IOStateR\x05state\"\x8f\x01\n" +
	"\x17DigitalIOAttachResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.hal.digitalio.IOStateR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\x05R\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp*2\n" +
	"\x06IOType\x12\t\n" +
	"\x05INPUT\x10\x00\x12\n" +
	"\n" +
	"\x06OUTPUT\x10\x01\x12\x11\n" +
	"\rBIDIRECTIONAL\x10\x02*\x1e\n" +
	"\vIODirection\x12\x06\n" +
	"\x02IN\x10\x00\x12\a\n" +
	"\x03OUT\x10\x01*'\n" +
	"\aIOState\x12\t\n" +
	"\x05ERROR\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x022\xa3\x03\n" +
	"\tDigitalIO\x12S\n" +
	"\vListDevices\x12\x16.google.protobuf.Empty\x1a*.hal.digitalio.DigitalIOListDeviceResponse\"\x00\x12U\n" +
	"\fSetDirection\x12+.hal.digitalio.DigitalIOSetDirectionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"\x04Read\x12#.hal.digitalio.DigitalIOReadRequest\x1a$.hal.digitalio.DigitalIOReadResponse\"\x00\x12G\n" +
	"\x05Write\x12$.hal.digitalio.DigitalIOWriteRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x06Attach\x12\x16.google.protobuf.Empty\x1a&.hal.digitalio.DigitalIOAttachResponse\"\x000\x01B\x11Z\x0f./protos;protosb\x06proto3"

var (
	file_pkg_dio_proto_rawDescOnce sync.Once
	file_pkg_dio_proto_rawDescData []byte
)

func file_pkg_dio_proto_rawDescGZIP() []byte {
	file_pkg_dio_proto_rawDescOnce.Do(func() {
		file_pkg_dio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_dio_proto_rawDesc), len(file_pkg_dio_proto_rawDesc)))
	})
	return file_pkg_dio_proto_rawDescData
}

var file_pkg_dio_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_dio_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_dio_proto_goTypes = []any{
	(IOType)(0),                          // 0: hal.digitalio.IOType
	(IODirection)(0),                     // 1: hal.digitalio.IODirection
	(IOState)(0),                         // 2: hal.digitalio.IOState
	(*IODevice)(nil),                     // 3: hal.digitalio.IODevice
	(*DigitalIOListDeviceResponse)(nil),  // 4: hal.digitalio.DigitalIOListDeviceResponse
	(*DigitalIOSetDirectionRequest)(nil), // 5: hal.digitalio.DigitalIOSetDirectionRequest
	(*DigitalIOReadRequest)(nil),         // 6: hal.digitalio.DigitalIOReadRequest
	(*DigitalIOReadResponse)(nil),        // 7: hal.digitalio.DigitalIOReadResponse
	(*DigitalIOWriteRequest)(nil),        // 8: hal.digitalio.DigitalIOWriteRequest
	(*DigitalIOAttachResponse)(nil),      // 9: hal.digitalio.DigitalIOAttachResponse
	(*emptypb.Empty)(nil),                // 10: google.protobuf.Empty
}
var file_pkg_dio_proto_depIdxs = []int32{
	0,  // 0: hal.digitalio.IODevice.type:type_name -> hal.digitalio.IOType
	1,  // 1: hal.digitalio.IODevice.direction:type_name -> hal.digitalio.IODirection
	3,  // 2: hal.digitalio.DigitalIOListDeviceResponse.devices:type_name -> hal.digitalio.IODevice
	1,  // 3: hal.digitalio.DigitalIOSetDirectionRequest.direction:type_name -> hal.digitalio.IODirection
	2,  // 4: hal.digitalio.DigitalIOReadResponse.state:type_name -> hal.digitalio.IOState
	2,  // 5: hal.digitalio.DigitalIOWriteRequest.state:type_name -> hal.digitalio.IOState
	2,  // 6: hal.digitalio.DigitalIOAttachResponse.state:type_name -> hal.digitalio.IOState
	10, // 7: hal.digitalio.DigitalIO.ListDevices:input_type -> google.protobuf.Empty
	5,  // 8: hal.digitalio.DigitalIO.SetDirection:input_type -> hal.digitalio.DigitalIOSetDirectionRequest
	6,  // 9: hal.digitalio.DigitalIO.Read:input_type -> hal.digitalio.DigitalIOReadRequest
	8,  // 10: hal.digitalio.DigitalIO.Write:input_type -> hal.digitalio.DigitalIOWriteRequest
	10, // 11: hal.digitalio.DigitalIO.Attach:input_type -> google.protobuf.Empty
	4,  // 12: hal.digitalio.DigitalIO.ListDevices:output_type -> hal.digitalio.DigitalIOListDeviceResponse
	10, // 13: hal.digitalio.DigitalIO.SetDirection:output_type -> google.protobuf.Empty
	7,  // 14: hal.digitalio.DigitalIO.Read:output_type -> hal.digitalio.DigitalIOReadResponse
	10, // 15: hal.digitalio.DigitalIO.Write:output_type -> google.protobuf.Empty
	9,  // 16: hal.digitalio.DigitalIO.Attach:output_type -> hal.digitalio.DigitalIOAttachResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_dio_proto_init() }
func file_pkg_dio_proto_init() {
	if File_pkg_dio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_dio_proto_rawDesc), len(file_pkg_dio_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_dio_proto_goTypes,
		DependencyIndexes: file_pkg_dio_proto_depIdxs,
		EnumInfos:         file_pkg_dio_proto_enumTypes,
		MessageInfos:      file_pkg_dio_proto_msgTypes,
	}.Build()
	File_pkg_dio_proto = out.File
	file_pkg_dio_proto_goTypes = nil
	file_pkg_dio_proto_depIdxs = nil
}
