//*
// DigitalIO Service.
//
// Service that enables a control of the Digital IO features of device

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/dio.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DigitalIO_ListDevices_FullMethodName  = "/hal.digitalio.DigitalIO/ListDevices"
	DigitalIO_SetDirection_FullMethodName = "/hal.digitalio.DigitalIO/SetDirection"
	DigitalIO_Read_FullMethodName         = "/hal.digitalio.DigitalIO/Read"
	DigitalIO_Write_FullMethodName        = "/hal.digitalio.DigitalIO/Write"
	DigitalIO_Attach_FullMethodName       = "/hal.digitalio.DigitalIO/Attach"
)

// DigitalIOClient is the client API for DigitalIO service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Service exposing DigitalIO functions.
type DigitalIOClient interface {
	// / Used to retrieve all available digital IO devices.
	ListDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DigitalIOListDeviceResponse, error)
	// / Used to set pin direction value of a particular gpio pin.
	SetDirection(ctx context.Context, in *DigitalIOSetDirectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// / Used to read value of a particular gpio pin.
	Read(ctx context.Context, in *DigitalIOReadRequest, opts ...grpc.CallOption) (*DigitalIOReadResponse, error)
	// / Used to write value of a particular gpio pin.
	Write(ctx context.Context, in *DigitalIOWriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// / Used to stream input events form device.
	Attach(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DigitalIOAttachResponse], error)
}

type digitalIOClient struct {
	cc grpc.ClientConnInterface
}

func NewDigitalIOClient(cc grpc.ClientConnInterface) DigitalIOClient {
	return &digitalIOClient{cc}
}

func (c *digitalIOClient) ListDevices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DigitalIOListDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DigitalIOListDeviceResponse)
	err := c.cc.Invoke(ctx, DigitalIO_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalIOClient) SetDirection(ctx context.Context, in *DigitalIOSetDirectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DigitalIO_SetDirection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalIOClient) Read(ctx context.Context, in *DigitalIOReadRequest, opts ...grpc.CallOption) (*DigitalIOReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DigitalIOReadResponse)
	err := c.cc.Invoke(ctx, DigitalIO_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalIOClient) Write(ctx context.Context, in *DigitalIOWriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DigitalIO_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalIOClient) Attach(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DigitalIOAttachResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DigitalIO_ServiceDesc.Streams[0], DigitalIO_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, DigitalIOAttachResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalIO_AttachClient = grpc.ServerStreamingClient[DigitalIOAttachResponse]

// DigitalIOServer is the server API for DigitalIO service.
// All implementations must embed UnimplementedDigitalIOServer
// for forward compatibility.
//
// *
// Service exposing DigitalIO functions.
type DigitalIOServer interface {
	// / Used to retrieve all available digital IO devices.
	ListDevices(context.Context, *emptypb.Empty) (*DigitalIOListDeviceResponse, error)
	// / Used to set pin direction value of a particular gpio pin.
	SetDirection(context.Context, *DigitalIOSetDirectionRequest) (*emptypb.Empty, error)
	// / Used to read value of a particular gpio pin.
	Read(context.Context, *DigitalIOReadRequest) (*DigitalIOReadResponse, error)
	// / Used to write value of a particular gpio pin.
	Write(context.Context, *DigitalIOWriteRequest) (*emptypb.Empty, error)
	// / Used to stream input events form device.
	Attach(*emptypb.Empty, grpc.ServerStreamingServer[DigitalIOAttachResponse]) error
	mustEmbedUnimplementedDigitalIOServer()
}

// UnimplementedDigitalIOServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDigitalIOServer struct{}

func (UnimplementedDigitalIOServer) ListDevices(context.Context, *emptypb.Empty) (*DigitalIOListDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDigitalIOServer) SetDirection(context.Context, *DigitalIOSetDirectionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDirection not implemented")
}
func (UnimplementedDigitalIOServer) Read(context.Context, *DigitalIOReadRequest) (*DigitalIOReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedDigitalIOServer) Write(context.Context, *DigitalIOWriteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedDigitalIOServer) Attach(*emptypb.Empty, grpc.ServerStreamingServer[DigitalIOAttachResponse]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedDigitalIOServer) mustEmbedUnimplementedDigitalIOServer() {}
func (UnimplementedDigitalIOServer) testEmbeddedByValue()                   {}

// UnsafeDigitalIOServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DigitalIOServer will
// result in compilation errors.
type UnsafeDigitalIOServer interface {
	mustEmbedUnimplementedDigitalIOServer()
}

func RegisterDigitalIOServer(s grpc.ServiceRegistrar, srv DigitalIOServer) {
	// If the following call panics, it indicates UnimplementedDigitalIOServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DigitalIO_ServiceDesc, srv)
}

func _DigitalIO_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIOServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalIO_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIOServer).ListDevices(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalIO_SetDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DigitalIOSetDirectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIOServer).SetDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalIO_SetDirection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIOServer).SetDirection(ctx, req.(*DigitalIOSetDirectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalIO_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DigitalIOReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIOServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalIO_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIOServer).Read(ctx, req.(*DigitalIOReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalIO_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DigitalIOWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalIOServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DigitalIO_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalIOServer).Write(ctx, req.(*DigitalIOWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalIO_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalIOServer).Attach(m, &grpc.GenericServerStream[emptypb.Empty, DigitalIOAttachResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DigitalIO_AttachServer = grpc.ServerStreamingServer[DigitalIOAttachResponse]

// DigitalIO_ServiceDesc is the grpc.ServiceDesc for DigitalIO service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DigitalIO_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hal.digitalio.DigitalIO",
	HandlerType: (*DigitalIOServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _DigitalIO_ListDevices_Handler,
		},
		{
			MethodName: "SetDirection",
			Handler:    _DigitalIO_SetDirection_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _DigitalIO_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _DigitalIO_Write_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _DigitalIO_Attach_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/dio.proto",
}
